---
title       : Coursera -  Developing Data Products
subtitle    : The Effectiveness of ASVAB Testing
author      : Tracy Wilson
job         : Senior Consultant
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Background

The American military recruits and trains a tremendous amount of new personnel every year.  To match people with skills, the armed forces recruits must take a test called the ASVAB.  This study will try to determine if the the ASVAB is an indicator of future success.

--- 

## ASVAB

The ASVAB was first introduced in 1968 and was adopted by all branches of the military in 1976. It underwent a major revision in 2002. In 2004, the test's percentile rank scoring system was renormalized, to ensure that a score of 50% really did represent doing better than exactly 50% of the test takers.

This application looks at ASVAB scores across three years and examines the difference in distribution between all students, students who successfully graduated and students who failed.

--- 

## The Application

The application allows you to look at 3 years worth of data.  The data is broken up into 3 different groups:  All data, Eliminations, and Grads.

--- 

## Expected Results

If the ASVAB is an indicator of suitability to the job being trained for, then the histogram should show a shift to the left when compared to All Data - and an even more pronounced shift when compared to students who successfully graduated




